name: Release Pipeline

on:
  push:
    branches:
      # Regular release channels
      - master
      - next
      - beta
      - alpha
      # Support, hotfix branches like: 1.0.x or 1.x
      - '([0-9]+)(\.([0-9]+))?\.x'

  # Allows triggering the workflow manually
  workflow_dispatch:
    inputs:
      payment_network:
        description: "Payment network (holesky, goerli, mainnet, mumbai, polygon, rinkeby)"
        required: false
        default: "holesky"
      provider_version:
        description: "Provider version (e.g., v0.15.2 or pre-rel-v0.15.1)"
        required: false
        default: "v0.15.2"
      requestor_version:
        description: "Requestor version (e.g., v0.15.2 or pre-rel-v0.15.1)"
        required: false
        default: "v0.15.2"
      provider_wasi_version:
        description: "Provider WASI version (e.g., v0.2.2)"
        required: false
        default: "v0.2.2"
      provider_vm_version:
        description: "Provider VM version (e.g., v0.3.0)"
        required: false
        default: "v0.3.0"

# We're going to interact with GH from the pipelines, so we need to get some permissions
permissions:
  contents: read # for checkout

env:
  PROVIDER_VERSION: ${{ github.event.inputs.provider_version || 'v0.15.2' }}
  REQUESTOR_VERSION: ${{ github.event.inputs.requestor_version || 'v0.15.2' }}
  PROVIDER_WASI_VERSION: ${{ github.event.inputs.provider_wasi_version || 'v0.2.2' }}
  PROVIDER_VM_VERSION: ${{ github.event.inputs.provider_vm_version || 'v0.3.0' }}
  PAYMENT_NETWORK: ${{ github.event.inputs.payment_network || 'holesky' }}

jobs:
  regular-checks:
    uses: ./.github/workflows/regular-checks.yml

  run-e2e-tests:
    name: Run E2E tests
    uses: ./.github/workflows/e2e-tests.yml
    needs: regular-checks

  run-cypress-tests:
    name: Run Cypress tests
    uses: ./.github/workflows/cypress-tests.yml
    needs: regular-checks

  run-examples-tests:
    name: Run Examples tests
    uses: ./.github/workflows/examples-tests.yml
    needs: regular-checks

  release:
    name: Release the SDK to NPM and GitHub
    needs: [run-e2e-tests, run-cypress-tests, run-examples-tests]
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          # Semantic release requires this as bare minimum
          node-version: 20

        # Why this? https://github.com/npm/cli/issues/7279
        # Why this way? https://github.com/actions/setup-node/issues/213
      - name: Install latest npm
        shell: bash
        run: |
          npm install -g npm@latest &&
          npm --version &&
          npm list -g --depth 0
      - name: Install dependencies
        run: npm install

      - name: Verify the integrity of provenance attestations and registry signatures for installed dependencies
        run: npm audit signatures

      - name: Build the SDK for release
        run: npm run build

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
run-name: "${{ github.workflow }} - Network: ${{ github.event.inputs.payment_network }}, Requestor: ${{ github.event.inputs.requestor_version }}, Provider: ${{ github.event.inputs.provider_version }}, WASI: ${{ github.event.inputs.provider_wasi_version }}, VM: ${{ github.event.inputs.provider_vm_version }}"
